spring.application.name=spring
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql= true 
spring.jpa.properties.hibernate.format_sql = true 
spring.jpa.open-in-view=false   


spring.security.user.name=admin
spring.security.user.password=admin


springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


spring.jackson.property-naming-strategy=SNAKE_CASE
